### PR TITLE
Add GeoJSON test fixture

### PR DESCRIPTION
**Pull request by DenisCarriere**
Added simple GeoJSON input/output fixture.

Strange output... 🤔 

image

image

It says here that `extent()` is not implemented, so maybe that's the reason why the strange output.

> voronoi.extent([extent]) and voronoi.size([size]) are not implemented.

### CODE REVIEW

**Comment by Fil** [comment]
The output you see is weird only because the viewer you use doesn't know how to display these big polygons, that are in the [d3 flavor of GeoJSON](https://github.com/d3/d3-geo).

Of course d3 views them perfectly
http://blockbuilder.org/Fil/8226c572488d813a4de6dfd50ec5ca50

(Feel free to change `d3.geoMercator` to some other projection or comment out line 153 to see the global thing).

**Comment by Fil** [comment]
Thank you!

**Comment by DenisCarriere** [comment]
OOOH I get it! 👍 

Yea https://geojson.io  might not do the trick for that type of GeoJSON output.

That sounds like it would be pretty tricky to support.

**Comment by Fil** [comment]
I don't know for turfjs, but in d3 we have antimeridian cutting, which you can get by applying an equirectangular transform, see https://github.com/d3/d3-geo/issues/113#issue-255965427

**Comment by DenisCarriere** [comment]
Interesting, I remember attempting this in the past and it's not an easy one, feel free to submit a PR if you find a solution for this.

**Pull request merged**
